services:
    app:
        build:
            args:
                # Não altere o nome de usuário abaixo
                user: dime
                uid: 1000
            context: ./
            dockerfile: ./docker/Dockerfile
        image: php84
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: erick-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/.bashrc:/home/dime/.bashrc
            - ./docker/php/auth.json:/home/dime/.composer/auth.json
        networks:
            - dev

    nginx:
        image: nginx:alpine
        container_name: erick-nginx
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - dev
        links:
            - app

    db:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: erick-db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
        ports:
            - "5432:5432"
        volumes:
            - arquivos_postgres:/var/lib/postgresql/data
        networks:
            - dev

volumes:
    arquivos_postgres:

networks:
    dev:
        driver: bridge
